### ISSUE TITLE
issue with otf opening

### ISSUE THREAD

**Issue by fabiorug** [aliftype/mada#41]
windows seven it doesn't open. transtype converter not, first two online converter not, onlinewebfonts converter not.

**Comment by khaledhosny** [comment]
It uses CFF2 table which is not widely supported.

**Comment by fabiorug** [comment]
can you upload a version without this variable thing?

**Comment by khaledhosny** [comment]
Not at the moment, but you can use the last release https://github.com/aliftype/mada/releases/tag/v1.3. I will probably sort this out when time comes to cut a new release.
